### ISSUE TITLE
Make this deployable on top of a https://github.com/Azure/data-landing-zone as a Data Product

### ISSUE THREAD

**Issue by MiguelElGallo** [Azure/azure-synapse-analytics-end2end#5]
Hi,
This looks great, but to be aligned with the data landing zone and the data management landing zone
https://github.com/Azure/data-management-zone
This should be deployable on top of data landing zone as data product, re-using the already provided services like networking, etc.
Thanks,

**Comment by fabragaMS** [comment]
We have work in progress to make that a reality. Please allow some time for work to be completed.

**Comment by fabragaMS** [comment]
#please-close
